### ISSUE TITLE
Update Task-1 and 2 Decision Phase titles

### ISSUE THREAD

**Issue by billuraksoy** [ianchadd/rpi_3208#119]
Task 2 is now Task 1 since we removed the ID creation task. However, in the decision stage, it says "Task 2 : Decision Phase". Please update it to Task 1: Decision Phase. 

Similarly, the title for Task 2 is currently "Task 3 : Decision Phase". It needs to be "2" instead of 3.

**Comment by boonhankoh** [comment]
agreed, we should also remove "phase".
