### ISSUE TITLE
Task: Investigate Image Upload issue and report back

### ISSUE THREAD

**Issue by ianchadd** [ianchadd/rpi_3208#130]
In app "image upload", I'm having some issues:

- Image preview does not work in Chrome
- I suspect this is from the CreateURL portion of the code in webcam.js, which apparently has been deprecated in Chrome
- image preview does work in Safari

Could you take a look at image upload and webcam.js (located in _static/image_upload) and let me know if you see a quick solution to this issue? Don't implement any code changes just yet, just comment on this Issue with your assessment.

**Comment by mcdaij** [comment]
Hi, so I downloaded it, looked through the files, didn't see any apparent programming issues, and hosted a local test server for it, worked fine on chrome for me with no error log output, chrome likes to hold on to js files in between sessions, have you tried clearing your cache or running it in an incognito window?

**Comment by mcdaij** [comment]
In case you didn't know, you can hard reload and clear your cache for just that page if you do Fn+F12 and then Ctrl+Shift+R or right click on the reload button and click "Hard Reload".

**Comment by ianchadd** [comment]
Thank you! Just tried it in incognito and it's all good. I'll test more later, but this seems to be "solved" (i.e. there was no issue in the first place).

**Comment by ianchadd** [comment]
This was working fine locally, but when I pushed it and deployed to the heroku site, it doesn't seem to work. 
Link to test here: https://rpi-3208-testing.herokuapp.com/join/3bbldxcxc3/

**Comment by ianchadd** [comment]
Solved
