### ISSUE TITLE
Re-align choice slider in dg decision template

### ISSUE THREAD

**Issue by ianchadd** [ianchadd/rpi_3208#132]
Template file: dg_qsp/decision_template

The slider (id = "myRange") currently has 0 [SLIDER] 100, aligned horizontally. 

Ideally, this would look like the screenshot included (i.e. no numbers, "Me" on the left and "[Partner ID]" on the right), but I couldn't find an easy solution for the alignment of all of this. Could you take a look and see if there is a quick solution to this?

Note: the appearance of the Offer page (which includes the decision_template) should not change. 

Also note: appearance can be tested using the QSP Dictator session config demo. 

<img width="533" alt="Screen Shot 2020-07-14 at 1 21 36 PM" src="https://user-images.githubusercontent.com/58232760/87456456-f73e1100-c5d4-11ea-9b37-741f4e0c2dfa.png">

**Comment by mcdaij** [comment]
So after digging around quite a bit it seems as though the inbuilt Otree slider is actually pretty resistant to customization. What they recommend in the docs is writing your own slider in JS and/or HTML and plugging that in. I could make that for you pretty easily and you'd have complete control over function and looks, in the meantime though I'll keep looking for a way to edit it within otree.

**Comment by mcdaij** [comment]
I might be able to just use CSS to change the formatting of it on the surface level as well

**Comment by ianchadd** [comment]
Thanks for looking into this. 

If you actually look at the decision_template file and the Offer.html template, the slider that is currently in use I coded using a combination of HTML, CSS, and JS. Really it's just an alignment issue at this point. Could you take a look at that code specifically?

Feel free at this point to implement any changes to decision_template and Offer.html to this end.

**Comment by mcdaij** [comment]
Hi sorry, my bad, I thought that the slider was specified by the oTree range code because of the appearance. Give me a few and I'll push a version and see what you think.

**Comment by mcdaij** [comment]
You don't have an ID being assigned to the dictator, so I'm not entirely sure what you want me to put there, but for the time being I'll just put "ME"

**Comment by mcdaij** [comment]
![qspSlider](https://user-images.githubusercontent.com/68068255/88090089-0b48bc00-cb5b-11ea-9798-544c6e0d7f4d.png)
Is this better?

**Comment by ianchadd** [comment]
It would be better if we had the following:

1. Slider takes up full width
2. Right side said "PARTNER: [Flag] [ID]" instead of using parentheses. 

Thanks!

**Comment by mcdaij** [comment]
![qspSliderV2](https://user-images.githubusercontent.com/68068255/88104291-3d184d80-cb70-11ea-89cb-5851b35bed84.png)
Sorry for the delay, pushing this, lmk if you have anything else you want done to it. I just change the html file, didn't have to change anything else.

**Comment by mcdaij** [comment]
Do you have a pref for what branch I push to?

**Comment by ianchadd** [comment]
Please push to testing. Thanks!

**Comment by ianchadd** [comment]
Looks good!

**Comment by ianchadd** [comment]
Jack - could you take another look at this issue asap? We've decided that it would be best if the slider could display the following:

ME: [my_amount] [slider] PARTNER: [Flag] [ID] [their_amount]

my_amount and their_amount are currently shown on Offer.html underneath the slider in the "Final Allocation" section, so there's no need to change the js for those objects, just move them to the left and right of the slider. This seems easy (and I'm sure is), but when I've done this in the past, the fields, IDs, text on either side of the slider resizes constantly whenever you move the slider. So we need a solution where that doesn't happen (fixed position and width, etc.).

**Comment by ianchadd** [comment]
Resolved
