### ISSUE TITLE
bugs on recipient code 

### ISSUE THREAD

**Issue by billuraksoy** [ianchadd/rpi_3208#139]
Bugs:

1- qsp_dg_recip_id/Results/4/
- [x] they should be able to move forward without selecting anything for the attention check
- [x] 2- after I finished Survey Part 1, it moved back to the beginning of the survey. I had to do Part 1 all over again. After I did part 1 again, it proceeded to part 2. 
- [x] 3- link link on dg_recip_survey_p2/Introduction/13/ takes me google.com

**Comment by ianchadd** [comment]
3 - use prediction payment pdf in Dropbox
