### ISSUE TITLE
Dictator Game:survey-1

### ISSUE THREAD

**Issue by billuraksoy** [ianchadd/rpi_3208#148]
On /Partner_Explain_2/17/

Can we update the section where we remind them how much they sent:

In Task 1, you sent [AmountSentID1] ECU to [Partner ID1].
{line space here}
In Task 2, you sent [AmountSentID2] ECU to [Partner ID2]. 	

In the current version, it is hard to tell the token numbers apart from the alpha-numeric part. And it looks crowded. Putting an extra space in between them should also help with that.

**Comment by boonhankoh** [comment]
Agreed with @billuraksoy . The output looks confusing. I will keep to what we originally had in the .docx file:

**You made the following decisions:**
(extra space)
In Task 1, you sent [AmountSentID1] ECU to [Partner ID1].
(extra space)
In Task 2, you sent [AmountSentID2] ECU to [Partner ID2].

**Comment by boonhankoh** [comment]
Can we also add minimum 5-char limit to response?

**Comment by ianchadd** [comment]
**Done**
