### ISSUE TITLE
Missing Dictator survey question:

### ISSUE THREAD

**Issue by boonhankoh** [ianchadd/rpi_3208#182]
To what extent do you agree with the following statement: “I care about what others think of my actions.”
[Strongly Agree, Agree, Neither Agree not Disagree, Disagree, Strongly Disagree]

(Question should be before survey_qsp/LGBT_Attitudes/24/)

**Comment by ianchadd** [comment]
Added - it's in the full sequence and will **also** be asked of recipients. I don't think it's particularly interesting for recipients, but it could be. If we want to remove for recipients, it's not that hard to do.

**Comment by ianchadd** [comment]
Update: doesn't apply
