### ISSUE TITLE
missing prolific page at the end -dictator

### ISSUE THREAD

**Issue by billuraksoy** [ianchadd/rpi_3208#191]
Do they need to enter their prolific ID again at the end? do we need to have a nicer end of study page? 

@boonhankoh  what do you think?

Currently, this is what happens:

![Screen Shot 2020-08-18 at 2 29 17 PM](https://user-images.githubusercontent.com/44884690/90551369-34ab3680-e15f-11ea-9416-f36b4615aeb3.png)

**Comment by boonhankoh** [comment]
I don't think the prolific ID is needed again. However, we should have a nice Thank you for participating page :)

I think there are settings to redirect the participants back to the Prolific page right at the end, isn't that correct @ianchadd ?

**Comment by ianchadd** [comment]
Added prolific page + logic to prolific page to push part_vars to csv file
