### ISSUE TITLE
Recipient Code - Flags shown

### ISSUE THREAD

**Issue by billuraksoy** [ianchadd/rpi_3208#196]
In the recipient code, we ask them about their beliefs about two hypothetical participants. We present their IDs (flag and alpha numeric). I do not see this information being recorded in the data. So It is not clear which IDs that the recipients are making decisions over.

**Comment by ianchadd** [comment]
Just did a bit of refactoring. Now all relevant variables are stored in participant_vars and then output to a player variable in the p_id_end app. So we just download that app and then clean up that one variable (similar to how this is handled in our competition code). 

Right now these IDs are saved as "other_id", "third_id", "other_flag", and "third_flag" in participant vars. If we dislike those names, it's actually easier at this point to rename them when we clean the data in Stata after collection
