### ISSUE TITLE
delete "consent" variable under qsp_dg_recip_intro and qsp_dg_recip_id

### ISSUE THREAD

**Issue by boonhankoh** [ianchadd/rpi_3208#197]
redundant variable, not used.

**Comment by billuraksoy** [comment]
There are a lot of redundant variables in the data file. I figured we will just clean them in stata. I am ok either way.

**Comment by boonhankoh** [comment]
Fine either way with me too - depends on what the output file will look like (so the deletion is either here or in the STATA .do file).

**Comment by billuraksoy** [comment]
Lets keep the "consent" variable in all experiments. It is silly and we know that you cannot move forward without consenting, but it may be relevant to IRB if we get audited. so lets get it documented and keep it.

**Comment by boonhankoh** [comment]
There is already a "consent" variable right at the start - that's the one that is recorded when subjects click consent, and I agree we should keep it. The other "consent" variables appear in all other apps - hence my suggestion to delete them.

The data file from otree can be really large and long, so best to drop variables that do not record anything.

**Comment by ianchadd** [comment]
Leaving this as-is. See #196 comment on refactoring - we won't be using any of the per-app data for analysis, so redundant variables are a non-issue from a data cleaning perspective
