### ISSUE TITLE
dg_recip_survey_p2 ERROR in variable capture

### ISSUE THREAD

**Issue by boonhankoh** [ianchadd/rpi_3208#201]
Partner 1 average amount captured under round 1 average
But Partner 1 demographics captured under round 2

Partner 2 average captured under round 2
Partner 2 inferred demo captured under round 3

**Comment by ianchadd** [comment]
This isn't a bug, but a feature of the way that I programmed this. We need to keep this in mind when we write the do file for data cleaning later.

**Comment by billuraksoy** [comment]
@ianchadd 
Since we need to keep this in mind for data codebook, shall we keep it open? or maybe you are planning to check all codebook labels independent of whether they are closed or not?

**Comment by ianchadd** [comment]
Agreed - reopened.
