### ISSUE TITLE
qsp_dg_dict_instructions redundant variables

### ISSUE THREAD

**Issue by boonhankoh** [ianchadd/rpi_3208#206]
consent
my_ID
random_ID
custom_ID
chooseID
attn_check_dog
my_flag
other_flag
show_ID
part_vars
adj_1 --- adj_10
inferred_gender --- inferred_ally
attn_check_3
ID_explain
higher_inferred_ally --- higher_inferred_orientation

**Comment by ianchadd** [comment]
See #198
