### ISSUE TITLE
survey_demographics BUG

### ISSUE THREAD

**Issue by boonhankoh** [ianchadd/rpi_3208#210]
If type something in OTHER despite not choosing OTHER, I can proceed. Is this something we are worried about?

This relates to questions for gender, sexuality, relationship status, ethnicity, religion, state lived in, state grew up in,

**Comment by billuraksoy** [comment]
I am not worried about this. If they want to give us extra info, it is fine. I doubt that anyone would do that without choosing other.

**Comment by ianchadd** [comment]
yeah I'm not worried about this either. If something is typed in OTHER, it will now be recorded in participant_vars, so the data isn't lost if they don't select OTHER. In any case, it seems not worth the coding time to change the error message logic.
