### ISSUE TITLE
gender_typicality/general.html - question to be coded

### ISSUE THREAD

**Issue by billuraksoy** [ianchadd/rpi_3208#217]
I am not sure how we should code this but we need to include the following question into gender_typicality/general.html 

Using a scale from 1 to 10, where 1 means not important at all and 10 means extremely important, how important do you think being faithful is for a successful marriage or serious committed relationship?
(1 = Not important; 10 = Very important)

**Comment by ianchadd** [comment]
I can take care of this edit once we merge yours

**Comment by billuraksoy** [comment]
@ianchadd the min should be 1, not 0.
