### ISSUE TITLE
gender typ. question to be discussed

### ISSUE THREAD

**Issue by billuraksoy** [ianchadd/rpi_3208#218]
Currently, we have the following question in the gender typ. survey:

Have you used chewing tobacco (such as Red Man, Garrett, or Beechnut) or snuff (such as Skoal, Skoal Bandits, or Copenhagen) at least 20 times in your entire life? (0 = No; 1 = Yes)

Additionally, there is another tobacco related question that was used in wave 3: 
Number of past thirty days chewed tobacco (0–30 days)	

I did not code this question. Do we need to? I think we can skip it.

**Comment by ianchadd** [comment]
I think we should - it's possible that for our sample, the binary variable won't pick up a gender (or SO) difference, but that the # of days one will. In any case, it should be easy to add and I think we should err on the side of collecting more survey data for the GT stuff. I'm happy to code this once we merge your edits into /testing

**Comment by ianchadd** [comment]
added this and #218 to GT app on the "random" page (lol)
