### ISSUE TITLE
QCP: Task: risk question missing 

### ISSUE THREAD

**Issue by billuraksoy** [ianchadd/rpi_3208#263]
The risk elication survey question is missing. Can you please put it back? It should come before the gender typi. questions.

**Comment by ianchadd** [comment]
Did we ever have risk elicitation? I'm looking in QCP demographics and it's not even in the models. 

In GT survey, we ask "I like to take risks" with Strongly Disagree to Strongly agree as options. Is that enough? or do you think we need more?

**Comment by billuraksoy** [comment]
It is in the survey questions word document (I had archived it earlier this week so its in that folder), but I guess it was never coded. 

Please rate your willingness to take risks in general using a 1 – 10 scale, where 1 = "completely unwilling to take risks" and 10 = "completely willing to take risks". 

we mentioned having a 1-10 radio button. But just an input box would be fine. If we use an input box, then the question needs to be revised slightly.

**Comment by ianchadd** [comment]
Ok just added that back in. Weird, I had the wording coded, but for a different project?
