### ISSUE TITLE
selection screen for Game 3/Game 4 Selection pushes invalid input with a valid input

### ISSUE THREAD

**Issue by ianchadd** [ianchadd/rpi_3208#271]
**Problem**
In the Selection screens (Selection.html) in apps Game_3 and Game_4, when you click on 0.25 piece rate on the next-to-last row and try to submit, it raises an invalid input error. Screenshot attached of this error. 

This is apparently caused by the switch_point not updating correctly when you click on 0.25 piece rate on this specific row. Line 120 checks whether the switch_point value is valid and displays invalid-selection-modal if it isn't. The main problem then appears to be that switch_point is not updating to a valid selection when you click on 0.25 piece rate on the next to last row. 

**Hints at where in code the issue is**
I think that the issue lies in Selection.html in the $('.switch_point').click code (starts line 90 in Selection.html for Game_4). This should change the switch_point to reflect the chosen prices. Notice that line 113 logs changed switch_point in the console, which helps in testing, since when you click 0.25 on the next to last row this change is not logged. When testing, you can also click elsewhere higher up on the table and see that the change to switch_point logs.

**Please note**
Whatever solution works for Selection.html in Game_4 would also need to be implemented in Game_3. 

![Screen Shot 2020-09-17 at 12 06 09 PM](https://user-images.githubusercontent.com/58232760/93510145-c63cce00-f8ee-11ea-98e3-73f1e8b1b60f.png)

**Comment by mcdaij** [comment]
Pushed a fix to testing

**Comment by ianchadd** [comment]
**Fixed**
Clicking 0.25 in the next to last row is no longer treated as an invalid option

**Problem**
This fix introduced new data issues. See screenshots. I clicked 0.25 at a price of 1.50 (next to last row), so the game_4_switch point should be 1.75 (lowest price at which I choose Tournament). But the participant_vars show that the switch is treated as 1.50. 

![Screen Shot 2020-09-18 at 10 29 25 AM](https://user-images.githubusercontent.com/58232760/93609887-60a61b80-f99a-11ea-8049-685eb451b68d.png)
![Screen Shot 2020-09-18 at 10 29 58 AM](https://user-images.githubusercontent.com/58232760/93609894-626fdf00-f99a-11ea-8460-47fd0663ca30.png)

**Comment by mcdaij** [comment]
So, I think I've fixed the bug, just wondering what the output is supposed to be if they click .25 on the last row?

**Comment by billuraksoy** [comment]
Jack, we had this exact issue in the past and our programmer then implemented a fix. We are not sure why their fix is not working now (maybe things got changed along the way?). Below is a screenshot of the explanation of their fix. 
In theory, you can set those variables to anything larger than 1.75 if the subject always selects the piece rate for all rows. However, please take a look at Theo's fix (below), the rest of the code and make that your solution fits well into the code. 

<img width="950" alt="Screen Shot 2020-09-20 at 12 06 30 PM" src="https://user-images.githubusercontent.com/44884690/93715831-bb29ae00-fb39-11ea-8d1a-fe1b18c43633.png">

**Comment by mcdaij** [comment]
I've discovered some issues with the existing implementation that were partially responsible for the error that sparked this. I'm still working to parse out the logic behind a couple of the decisions.

**Comment by mcdaij** [comment]
Sorry this is taking so long, none of the code is commented and it's a bit obtuse in places.

**Comment by mcdaij** [comment]
I fixed the JavaScript to output what the backend code expects, in the format it expects, and I cleaned it up a bit, but after pouring over the code that's there on the backend, I'm still not entirely sure that the backend is going to do what I think y'all want it to. The radio button field is printing into the data table correctly, but from there on I'm not confident.

**Comment by ianchadd** [comment]
This specific issue is not happening anymore.
