### ISSUE TITLE
Edit to Selection in Games 3 and 4

### ISSUE THREAD

**Issue by ianchadd** [ianchadd/rpi_3208#274]
**Problem**
Current selection.html screen is broken and less clear than it needs to be. 

**Note**
This issue replaces any requested changes in #272 and #273. Any edits you make to Game 3 should also be done to Game 4. 

**Fix** 
Edit models.py, pages.py, and Selection.html in Game 3 and Game 4 code to re-structure the Selection environment. 

**Itemized Edits**
1. models.py: game_3_switch (game_4_switch for game 4) will not be an IntegerField where the choices should be dynamic and depend on Constants.round_values. The options should include round_values and round_values[-1]+0.001. The choice labels should be as follows (for the current round_values):

o	I would like to enter the tournament no matter what the tournament prize is [i.e. game_3_switch == 0.25]
 o	I would like to enter the tournament if the tournament prize is $0.50 or higher 
 o	I would like to enter the tournament if the tournament prize is $0.75 or higher 
 o	I would like to enter the tournament if the tournament prize is $1 or higher 
 o	I would like to enter the tournament if the tournament prize is $1.25 or higher 
 o	I would like to enter the tournament if the tournament prize is $1.50 or higher
 o	I would like to enter the tournament if the tournament prize is 1.75
 o	I would not like to enter the tournament no matter what the tournament prize is [i.e. game_3_switch == 1.751]

2. Get rid of entire table in Selection.html and simply have game_3_switch as a field. Keep the text at the top of the screen for now - Dr. Aksoy and I will make text edits later as we see fit. 
3. Edit pages.py to get rid of vars for template that are not necessary now (since we don't need to check the table input against valid inputs coming from round_values).

**Comment by ianchadd** [comment]
Also - I will work on this in /testing in tandem, so please let me know via email if you sit down to this.

**Comment by ianchadd** [comment]
Just pushed some edits to selection, pages, and models for game 3 that I believe solve this. Changes found in /testing

**Comment by mcdaij** [comment]
Hi, sorry, just saw this. Just looked over the changes you made and it looks like you solved the problem already. Sorry I didn't see this sooner!
