### ISSUE TITLE
QCP: debriefing survey?

### ISSUE THREAD

**Issue by billuraksoy** [ianchadd/rpi_3208#284]
Shall we put a debriefing survey at the very end? This would give us an idea if we end up getting crappy data or something. 

We can have the same two questions as the Discr. project and maybe also add a free text question (they would not have to answer in order to proceed).

**Comment by ianchadd** [comment]
Added feedback_survey_qcp to the app sequence with two fields from qsp + "Do you have any additional feedback (e.g. clarity of instructions, enjoyment of study)?" and a long string field.
