### ISSUE TITLE
game 3 title for tournament 

### ISSUE THREAD

**Issue by billuraksoy** [ianchadd/rpi_3208#287]
The title says **Game 3 Piece Rate** even when the payment scheme is chosen to be tournament. Can you make this conditional on the chosen scheme? If not, it can be just **Game 3**

![image](https://user-images.githubusercontent.com/44884690/94703729-2713cf80-030d-11eb-9667-935e5dbacc7b.png)

**Comment by ianchadd** [comment]
Changed it so it just says "Game 3". We already include the payment information in the previous screen and in the paragraph below the title here
