### ISSUE TITLE
First "Evaluation" page layout change and text edit requests

### ISSUE THREAD

**Issue by billuraksoy** [ianchadd/rpi_3208#33]
I suggest making this edits/changes to the evaluation page:
1. I think we should display the flags next to each other in a 2x2 table manner:
Your ID:          Other's ID
flag+id.           flag + id
To do this, we should decrease the font size a little bit, say 25-30%. 

2. Remove "Consider the ID shown below."

3. A minor edit to text (in bold)

"**Above, you see your ID on the left and another person's ID on the right.** Suppose you saw this ID and knew that it had been selected by another person in the same way as you selected your own ID for this survey (i.e. they were given a randomly generated alpha-numeric string of characters and chose the icon).

4. A minor edit to the next paragraph: 
Original: "Please provide at least three words/phrases that you think best describe **the individual whose ID is** "[flag] **hjlxc121**" ... " 
-also can you please make the alpha-numeric part in bold here. 

Thoughts? @ianchadd  @boonhankoh

**Comment by boonhankoh** [comment]
1. I agree with Billur's comment about displaying the flags next to each other in a 2x2 table manner.

2. However, I would suggest the following (I built on Billur's edited text - note that there are some small edits I made to the last paragraph):

Below, you can see your own ID on the left and a different ID on the right.

[TABLE]

Suppose the ID on the right has been selected by another person in the same way as you selected your own ID for this survey (i.e., they were given a randomly generated alpha-numeric string of characters and chose the icon).

Please provide at least **three** words/phrases that you think best describe **[flag] XXXXXX**. You need to provide at least three distinct words/phrases, but you may provide more (up to 10) if you wish.

See if you agree with this version instead? @billuraksoy @ianchadd

**Comment by boonhankoh** [comment]
Also, can we replace "Evaluation" with something else as the title? E.g., something generic like "Questionnaire"?

**Comment by billuraksoy** [comment]
Agreed with everything. As for item 4 regarding the flag size in text, I agree that it could be a little smaller but I am not too worried about it. We can try a smaller size and see how it looks.

**Comment by ianchadd** [comment]
Did all of the above (including getting rid of title per my response to #35. See screenshot below for an example of what this looks like now (for reference without having to test)
![Screen Shot 2020-03-12 at 2 49 56 PM](https://user-images.githubusercontent.com/58232760/76556946-e50a6580-6470-11ea-91af-ca8451a5fcf7.png)

**Comment by billuraksoy** [comment]
Great thanks Ian!   Would it be possible to make those IDs on top a little smaller and put a larger gap in between them if it is not too much work?

**Comment by ianchadd** [comment]
![Screen Shot 2020-03-12 at 4 26 36 PM](https://user-images.githubusercontent.com/58232760/76563685-4422a700-647e-11ea-8790-bde6bf256761.png)

Downsizing a bit looks like it took care of the crowding. Let me know if this works.

**Comment by billuraksoy** [comment]
yes this looks great.
