### ISSUE TITLE
Second "Evaluation" layout change and minor text edits

### ISSUE THREAD

**Issue by billuraksoy** [ianchadd/rpi_3208#34]
1.  we agree on #33 , we need to make the same layout change here on this second evaluation page. 

2. Text changes (in bold):
"Suppose you saw this ID **on the right** and knew that it had been selected by another person in the same way as you selected your own ID for this survey (i.e. they were given a randomly generated alpha-numeric string of characters and chose the icon).

3. Can you please make the alpha-numeric parts of the other's ID bold on this page?

**Comment by boonhankoh** [comment]
1. See #33 for my suggested edit of the paragraph before and just after the table with the 2 flags.

2. I agree with Billur's comments.

3. Last two questions, can you underline or bold "economics" and "social"?

**Comment by billuraksoy** [comment]
agreed.

**Comment by ianchadd** [comment]
Did all of the above except numbering questions - not sure how to do this automatically, little time-consuming to do it manually. I'll add another issue to track how to do this, but it's minor so I'll prioritize other concerns first
