### ISSUE TITLE
Reasons for Icon Selection page- title change

### ISSUE THREAD

**Issue by billuraksoy** [ianchadd/rpi_3208#35]
This page is also title "evaluation" and this is where we ask our subjects to tell us why they chose that specific flag. 

We can just delete the title on this page I think. We have too many pages with "evaluation" title. Or we can rename it? maybe like "Your Icon Selection"? 
Thoughts? 
@boonhankoh  @ianchadd

**Comment by boonhankoh** [comment]
I don't like the titles in general. Can we just keep them as "Questionnaire" in general for the entire survey?

**Comment by billuraksoy** [comment]
agreed.

**Comment by ianchadd** [comment]
actually just got rid of them entirely. We now only have titles for just instructions pages, consent, prolific ID entry, etc. Anywhere where a person makes a choice now has no title (I don't think they are necessary)
