### ISSUE TITLE
Final page text edits

### ISSUE THREAD

**Issue by billuraksoy** [ianchadd/rpi_3208#38]
Original "Thank you for participating in this survey. We will process your payment after the final submission of this survey (usually within 48 hours).

Before you close out this window, please fill out the form below.

Paste your Prolific ID here:"

I suggest "Thank you for participating in this survey. We will process your payment after the final submission of this survey (usually within 48 hours).

Paste your Prolific ID here:"

**Comment by boonhankoh** [comment]
I'd suggest changing it to

"Thank you for participating in this study. We will process your payment shortly (usually within 48 hours).

**Please enter your Prolific ID again.**"

[Bold the last sentence]

**Comment by billuraksoy** [comment]
agreed.
