### ISSUE TITLE
Attention Check Questions

### ISSUE THREAD

**Issue by billuraksoy** [ianchadd/rpi_3208#39]
Shall we put some attention check questions here and there? We can add one on the page where we ask some multiple choice questions about the other person and another one in the final survey about the participants.

**Comment by boonhankoh** [comment]
I don't think this is necessary. The survey is sufficiently short...

**Comment by billuraksoy** [comment]
I would feel better if we put at least one. We can place one in the survey.

**Comment by ianchadd** [comment]
Add the following:
- [ ] check in other ID eval page
- [ ] check in demographic survey
- [ ] wording in Instructions about attention checks

**Comment by boonhankoh** [comment]
Sure, that's fine with me.
