### ISSUE TITLE
Informed consent document

### ISSUE THREAD

**Issue by boonhankoh** [ianchadd/rpi_3208#40]
There is this paragraph on payment and compensation. For the survey, there are no bonus payments (I think?), so maybe we should just keep the first sentence (and shorten it) and the last sentence: "You will be given $2 for participating in this study. Your earnings will be disbursed via prolific."

PAYMENT AND COMPENSATION
You will be given $2 for participating in this study in addition to more money depending on your choices in this experiment and on the decisions of othersds. Because the study features real economic decisions, you will have the opportunity to receive additional rewards. The amount you receive will depend on your decisions, the decisions of others, and luck. For these reasons we cannot predict exactly how much you will make. All of your earnings will be disbursed via prolific.

**Comment by boonhankoh** [comment]
I just realised that the informed consent form has the IRB stamp, so editing it may not be possible. Hence, feel free to ignore this issue (it's a small one anyway).

**Comment by billuraksoy** [comment]
not possible to edit without circulating via IRB.

**Comment by ianchadd** [comment]
Not doing this
