### ISSUE TITLE
BUG: Currently not allowing me to go past the first survey page (after asking me about partner's demographics). Error message:

### ISSUE THREAD

**Issue by boonhankoh** [ianchadd/rpi_3208#62]
Server Error (500)
There are several ways to find the cause of the issue:

Delete the OTREE_PRODUCTION environment variable and reload this page
Look at your Sentry messages (see the docs on how to enable Sentry)
Look at the server logs

**Comment by boonhankoh** [comment]
@ianchadd

**Comment by ianchadd** [comment]
This is fixed now
